### ISSUE TITLE
Add brand.yml

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/assets#17]
https://github.com/posit-dev/brand-yml/issues/53

Noting from the issue that NHS England does not cover the other Nations in their branding. NHS-R Community uses NHS England branding but we often use the least used colours (the pinks and greens for example).

**Comment by Lextuga007** [comment]
@send2dan my interest (and ultimately control) is for NHS-R Community branding as I'm unsure how NHS England feel about their details or branding being used if we submit on their behalf. NHS-R uses the colours under the copyright agreement https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/ so you can get the same England NHS colours and avoids the assumption that NHS England have approved this submission. It might be that they are fine with this but this needs to be checked and could cause undue delays.

**Comment by send2dan** [comment]
OK, so are you simply proposing that the outcome of [https://github.com/posit-dev/brand-yml/issues/53](https://github.com/posit-dev/brand-yml/issues/53) could be hosted at [https://github.com/nhs-r-community/assets](https://github.com/nhs-r-community/assets)?

**Comment by Lextuga007** [comment]
Sorry, I've just realised I've effectively tagged the original issue by referencing it and that's slightly out of context. 

This is an issue that I'll use to reference in this repo the NHS-R Community brand.yml and then I'll do a PR to the posit-dev repo for the Gallery on behalf of NHS-R Community which uses the NHS England colour branding.
