### ISSUE TITLE
Logo doesn't render from code in README

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/assets#2]
The link to the logo image is broken. Replace with https://raw.githubusercontent.com/nhs-r-community/assets/main/logo/nhsr-logo.svg

**Comment by Lextuga007** [comment]
I think I messed up the pull request because I did 5 before 4 so I've overwritten the change you made in 4!

**Comment by mrugank-wadekar** [comment]
That wouldn't be an issue, because I accidentally created a pull request two times!
Sorry for the trouble!
Is everything fixed and up to date now?

**Comment by Lextuga007** [comment]
Oh I see 😄 I'm a bit muddled too apologies! If you want to update the second url - the one that just appears in the README to be copied that's great. Not to worry if you want to leave it; I can update later if need be. Thanks for having a go though - it's always difficult making that first pull request so thanks for contributing! Much appreciated 🚀

**Comment by Lextuga007** [comment]
All sorted now 😃 thanks for persevering! Your contribution is really appreciated and I hope you contribute again in the future!
